services:
  - type: web
    name: evalx-web
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start:web
    envVars:
      - key: NODE_ENV
        value: production
  - type: worker
    name: evalx-worker
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm run start:worker
    envVars:
      - key: NODE_ENV
        value: production
